image: jekyll/jekyll

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

#before_script:
#  - bundle install

pages:
  stage: deploy
  script:
  #- gem install jekyll 3.8.6
  - jekyll build -d _site
  artifacts:
    paths:
    - _site
  only:
    - master
