# Site settings
title: Rust LATAM | May, 22nd-23rd 2020 | Mexico City
email: info@rustlatam.org
url: https://www.rustlatam.org
baseurl: ""
description: "Where Rust meets Latin America"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#273b91'
  links: '#65a2b3'

# Footer settings
footer: Rust LATAM

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/RustLatamConf
  - title: gitlab
    url: https://gitlab.com/rustlatam/website-2020
  - title: discord
    url: https://discord.gg/DsQ5JG

# Build settings
markdown: kramdown
permalink: pretty
